describe('Verifikasi Fitur Login Akun', () => {
  it('User Berhasil Login dengan data akun yang terdaftar', () => {
      cy.visit('https://www.saucedemo.com')
      cy.get('[data-test="username"]').type("standard_user")
      cy.get('[data-test="password"]').type("secret_sauce")
      cy.get('[data-test="login-button"]').click()  
      cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
      cy.get('[data-test="shopping-cart-link"]').click()
      cy.get('[data-test="checkout"]').click()
      cy.get('[data-test="firstName"]').type("Ricky")
      cy.get('[data-test="lastName"]').type("Sanjaya")
      cy.get('[data-test="postalCode"]').type("17141")
      cy.get('[data-test="continue"]').click()
      cy.get('[data-test="subtotal-label"]').should('have.text','Item total: $29.99')
      cy.get('[data-test="finish"]').click()
      cy.get('[data-test="complete-header"]').should('have.text','Thank you for your order!')
      cy.get('[data-test="complete-text"]').should('have.text','Your order has been dispatched, and will arrive just as fast as the pony can get there!')
  })
})